### ISSUE TITLE
Getting error "This page isn’t working - HTTP ERROR 500" to check the scheduler logs or the failed backups

### ISSUE THREAD

**Issue by donsan-git** [cBackup/main#74]
Hi,
I am getting the below error when trying to go to "Failed" backup nodes in the dashboard or trying to go to scheduler logs.
This page isn’t working - HTTP ERROR 500
I checked one of the previous cases and changed the "memory_limit" setting in /etc/php.ini from 128M to 1024M.
Also, checked the application log in /opt/cbackup/runtime/logs/app.log. The corresponding log message is given below. Could you please help?

$_POST = []
2021-12-21 07:43:42 [127.0.0.1][-][-][error][yii\web\HttpException:400] yii\web\BadRequestHttpException: Unable to verify your data submission. in /opt/cbackup/vendor/yiisoft/yii2/web/Controller.php:166
Stack trace:
#0 /opt/cbackup/vendor/yiisoft/yii2/base/Controller.php(155): yii\web\Controller->beforeAction(Object(yii\base\InlineAction))
#1 /opt/cbackup/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('maintenance', Array)
#2 /opt/cbackup/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('site/maintenanc...', Array)
#3 /opt/cbackup/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#4 /opt/cbackup/web/index.php(38): yii\base\Application->run()
#5 {main}

Thank you in advance!

Regards'
Sanjeeva

**Comment by donsan-git** [comment]
I had also tried with system update. But, no luck!

Regards'
Sanjeeva

**Comment by donsan-git** [comment]
SOMEONE PLEASE HELP
Below is the entry in the /opt/cbackup/runtime/logs/app.log when I tried to go to scheduler logs or to list the Failed nodes from dashboard
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
#1 {main}
2021-12-28 11:46:19 [103.24.173.18][ADMIN][p31cvrght2mk76982857sp1m86][info][application] $_GET = [
    'r' => 'log/scheduler/list'
    'LogSchedulerSearch' => [
        'severity' => 'ERROR'
        'date_from' => '2021-12-28 00:00'
        'date_to' => '2021-12-28 11:45'
    ]
]

**Comment by donsan-git** [comment]
The problem is solved when I further increased the memory_limit in /etc/php.ini to 2048M. However, it is running slow, 
I have another instance which is running fine with 128M itself and with good performance. There is something wrong or to be tuned!

**Comment by donsan-git** [comment]
I am still keeping this open as I want to see if there is any other issue (root cause)!

**Comment by fcs90096** [comment]
I am also seeing this issue on our server as well. Any help would be appreciated.
